package com.desmond.ofd.catalog

import android.content.Context
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * Loads `assets/catalog.json` (generated by `parse_catalog.py` from KHwang9883/MobileModels +
 * danielspringer's site catalog). Schema:
 * ```
 * { "PLK110": { "name": "OnePlus 15", "regions": ["CN"] }, ... }
 * ```
 *
 * Both [DeviceCatalog] (object lookup) and [CatalogRepository] (full list) read through this
 * single in-memory cache.
 */
@Serializable
data class CatalogEntryDto(
    val name: String,
    val regions: List<String> = emptyList(),
)

object DeviceCatalog {
    @Volatile private var cached: Map<String, CatalogEntryDto>? = null
    private val parser = Json { ignoreUnknownKeys = true }

    fun load(context: Context): Map<String, CatalogEntryDto> {
        cached?.let { return it }
        val map = runCatching {
            context.assets.open("catalog.json").bufferedReader(Charsets.UTF_8).use { reader ->
                parser.decodeFromString<Map<String, CatalogEntryDto>>(reader.readText())
            }
        }.getOrElse { emptyMap() }
        cached = map
        return map
    }

    fun marketingName(context: Context, model: String): String? =
        load(context)[model]?.name

    fun regions(context: Context, model: String): List<String> =
        load(context)[model]?.regions ?: emptyList()
}
